spring:
  data:
    mongodb:
      uri: mongodb+srv://archit:Archit309@cluster0.vv3wgio.mongodb.net/?appName=Cluster0
      database: journal_db
      auto-index-creation: true

server:
  port: 8080

